### ISSUE TITLE
before or beforeAll 

### ISSUE THREAD

**Issue by deshdeep-airwallex** [Bkucera/cypress-plugin-retries#9]
Hey @Bkucera, 

Firstly appreciate for coming up with this plugin it's a big help. 
I have more of a question as Cypress uses Mocha and there is no 
`beforeAll` in Mocha why would Cypress identifies it as beforeAll? Please, refer the image below: 

![image](https://user-images.githubusercontent.com/27190318/55475525-e2e43800-565f-11e9-82bd-d8e5559fa799.png)
As you have specified in README `beforeAll` wouldn't be retried. Is there alternative for this as i want to create user and pre test stuff before my it blocks.
Cheers!

**Comment by Bkucera** [comment]
Hi, we use the term beforeAll because it's more clear than saying before, but I can see how that's confusing.

A before is only ever ran once, not once per test like a beforeEach, and you shouldn't be putting test code like assertions in there. It's meant for one-time setup code. For this reason, we do not retry it. But then again I may be misunderstanding you.

I also notice you have synchronous code in between your before and beforeEach code blocks, which will be run before either of them execute, so setLocalstorage() is called before any of your hooks or tests run

**Comment by deshdeep-airwallex** [comment]
Hi @Bkucera 

Thanks for looking in to it. My intent is to create a single user per describe block and login once. As you can see I create a user followed by some other stuff and login that's just to avoid login for each tests. 

`let LOCAL_STORAGE_MEMORY = {};

Cypress.Commands.add('saveLocalStorage', () => {
  Object.keys(localStorage).forEach((key) => {
    LOCAL_STORAGE_MEMORY[key] = localStorage[key];
  });
});

Cypress.Commands.add('restoreLocalStorage', () => {
  cy.server();
  cy.route('/api/reauth').as('reauth');
  Object.keys(LOCAL_STORAGE_MEMORY).forEach((key) => {
    localStorage.setItem(key, LOCAL_STORAGE_MEMORY[key]);
  });
});

export const setLocalStorage = () => {
  beforeEach(() => {
    cy.restoreLocalStorage();
  });
  afterEach(() => {
    cy.saveLocalStorage();
  });
  after(() => {
    LOCAL_STORAGE_MEMORY = {};
  });
};`

**Comment by Bkucera** [comment]
@deshdeep-airwallex I see, so which hooks would you like to retry? the `before` hook?

**Comment by Livian95** [comment]
Hey @Bkucera , I really appreciate your work, this plug-in basically solved almost all of our problems on fleaky tests ( blame the application ). But i see you did not answer to this, can you please tell me if there is any possible way to retry a beforeAll hook ? The reason I want to retry it it's because sometimes because how the app is built, I receive 502's and 401's, and there is no issue there, just fleakyness, so can you please tell me if there is any way I can retry a beforeAll that has been putted in support/index ?

**Comment by symon-skelly** [comment]
I would also love to see this, especially with the firefox cookie issue that is occurring at the moment.

https://github.com/cypress-io/cypress/issues/6375

Every other test fails for me using firefox at present.

If I re-run the test after the error occurs it works perfectly, how difficult would it be to allow the beforeEach(before) function to be retried?

**Comment by Bkucera** [comment]
@symon-skelly the beforeEach functions are currently retried. beforeAll are not.
